### ISSUE TITLE
request category error

### ISSUE THREAD

**Issue by Tomo-ja** [yk-jp/expense-tracker-backend#17]
unexpected category type by the url

**Comment by Tomo-ja** [comment]
[](url)
![Screen Shot 2022-09-05 at 7 44 49 PM (2)](https://user-images.githubusercontent.com/89565258/188536195-55a2c0ef-fa6e-4511-ae74-622821f7c3b4.png)

**Comment by yk-jp** [comment]
'Type(Income/Expense)' was not added and data was always overwritten in the cache.  

<img width="470" alt="Screen Shot 2022-09-05 at 8 02 39 PM" src="https://user-images.githubusercontent.com/69574727/188538262-8c2b5b96-98f3-4100-87ef-6edf0ab6665a.png">
